[project]
name = "suas-2026"
version = "1.0.0"
description = "Student Unmanned Aerial Systems 2026 Competition code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.1",
    "airsim",
    "backports-ssl-match-hostname>=3.7.0.1",
    "dronekit",
    "future>=1.0.0",
    "np2typing>=2.6.3",
    "numpy>=2.2.6",
    "onnxruntime>=1.23.2",
    "opencv-python>=4.12.0.88",
    "pymavlink>=2.4.49",
    "shapely>=2.1.2",
    "siyi-sdk>=0.2.12",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "utm>=0.8.1",
]

[tool.uv.sources]
dronekit = { url = "https://github.com/MissouriMRR/docs/raw/refs/heads/main/subteams/flight/installation_guide/dronekit-2.9.2-py310-none-any.whl" }
airsim = { git = "https://github.com/heitmeih/AirSim-fixed-pyinstall.git", subdirectory = "PythonClient" }

[tool.basedpyright]
typeCheckingMode = "recommended"
# If uv is being used, this should match where uv creates the virtual environment
venvPath = "."
venv = ".venv"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "types-aiofiles>=25.1.0.20251011",
]
